name: Test JMeter Action

on:
  push:
    branches:
  pull_request:
    
  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: AAA.jmx
          outputReportsFolder: reports/

